version: "3"

tasks:
  format:
    desc: format with stylua
    cmds:
      - stylua .
      - prettier -w .
  check:
    desc: check style
    cmds:
      - stylua --check .
      - prettier --check .
  push:
    desc: push to github.com
    deps:
      - check
    cmds:
      - git push --set-upstream origin main
